### ISSUE TITLE
[gixp pack-receive] The first proper fetch to a bare repository

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#104]
Do what's needed to fetch as good as git does (on a bare repository, one without a working tree). This particularly includes proper ref handling as well as safety in the light of concurrent repository access.

### Tasks

* [ ] `git-refs` - write loose refs and handle the git reflog, temp files, lock files
* [ ] `git-protocol` - fetch negotiation with wants and haves. Implementation should be easily usable potentially as base implementation of the delegate.
* [ ] `git-pack` - assure packs are written safely, that is won't interfere with multi-packs or other pack writers writing the very same pack. Check how locking works.

**Comment by Nytelife26** [comment]
What's the status on `gixp clone`? I'm very much interested in helping out on that front.

**Comment by Byron** [comment]
`gixp clone` as it's seen here would only clone bare repositories. The biggest requirement for achieving work tree checkouts is to implement `git-index`. Doing so requires a serious investment in time and great attention to detail. There may be smaller tasks on the way but ultimately, `git-index`  is what's needed to clone a repository with work tree.

If this is outlook isn't too frightening for you, I'd be happy to get you involved in some capacity.

**Comment by Nytelife26** [comment]
I have never contributed to gitoxide so I'm not too familiar with it yet, but I learn things quickly - nothing frightens me :) so yes, I'm more than happy to try things out if you give me some pointers in the right direction.

**Comment by Byron** [comment]
Have you had a chance to check out the backlog here? https://github.com/Byron/gitoxide/projects/1 

A good way to get acquainted with `gitoxide` would probably be to use it by further oxidizing some crates that are using `git2` ATM but could already use `gitoxide`. This would inevitably lead to some features being implemented or improved on on the way.

Speaking of feature, I think desperately needed is [commit ancestor traversal sorted by commit time](https://github.com/Byron/gitoxide/projects/1#card-69834523).

A way forward would be for you to find something you are comfortable to get started, then we could kick it off in a 1:1 even.

Just let me know.

PS: I connected to you on keybase, a way to reach out to me in a more realtime and private fashion, as needed.

**Comment by pwnorbitals** [comment]
@Nytelife26 @Byron Had the chance to get progress on this one ? :)

**Comment by Byron** [comment]
All building blocks for a bare clone exist, they haven't been put into a cohesive package though.

A [non-bare clone](https://github.com/Byron/gitoxide/projects/1) is in the works which will include the bare one by its very nature.

**Comment by sharifhsn** [comment]
The cohesive package now exists. #551 added bare clone. Non-bare clone is implemented as well, tracked in #303.

The building blocks are now wired together behind a single entry point: `gix::prepare_clone_bare(url, path)?.fetch_only(…)` (and `gix::prepare_clone(…)?.fetch_then_checkout(…)` for the worktree case), exposed on the CLI as `gix clone [--bare]`.

Missing checkboxes now complete:

- **turn `gixp pack-receive` into `gixp clone` … cloning the first pack** — #551: creates the repository and fetches the first pack into it (`gix::prepare_clone_bare` / `gix clone --bare`).
- **a tool to fetch into an existing repository, creating a new pack and writing refs using transactions** — #548: `gix fetch` writes the received pack and updates refs through `gix-ref` transactions, with fast-forward handling.
- **investigate fetch negotiation … make it readily reusable via `git-protocol`** — #861: the `consecutive` algorithm was extracted into the reusable `gix-negotiate` crate and wired into `gix-protocol`, replacing the naive negotiator that failed against some servers.

**Comment by Byron** [comment]
Thanks for the hint. `gixp` isn't a thing anymore either, it's now just `gix`.
