### ISSUE TITLE
Sovereign Tech Fund and NLNet Application

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#1406]
This issue tracks the status for the application to https://www.sovereigntechfund.de (STF)  as well as to https://nlnet.nl .

Note that the STF is mutually exclusive, but the idea is to have options.

### Tasks

* [ ] Apply to STF
* [ ] Apply to NlNet
* [ ] figure out how to receive funds
* [ ] figure out how to spend funds

**Comment by EliahKagan** [comment]
Thanks! I've joined the [organization](https://github.com/GitoxideLabs).

(By the way, it looks like the link above, in the 2024-10-11 section, is broken: Even though it looks like the organization was initially named `Gitoxide-Labs` and then renamed to `GitoxideLabs`, [the URL with `Gitoxide-Labs`](https://github.com/organizations/Gitoxide-Labs) does not redirect to [the URL with `GitoxideLabs`](https://github.com/GitoxideLabs).)

**Comment by Byron** [comment]
Thank you for joining, and thanks for all the useful hints :). The link above is now fixed, and I set my group membership to public as well.

**Comment by Byron** [comment]
Moved to [this Tasks Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2804). This issue is being closed because task tracking now lives in Discussions.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
