### ISSUE TITLE
Fix loose db namespace and move packed-buffer handling into loose ref store

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#263]
The loose ref db needs to loose its built-in namespace as it' won't work well in a multi-threaded context unless each thread has their own loose ref DB. The latter is possible, but will stop working once ref-table arrives. So we need to refactor.

Currently the loose ref DB is `Sync`, but only awkwardly usable due to its packed-buffer being outsourced into the callers responsibility.

`git-repository` works around this by putting `packed-refs` into a thread-local cache. The latter isn't optimal as it might well be shared across threads.

The new store should be `Sync`, be prepared for `ref-table` (and to unify both loose and ref under one API), and store packed-refs in a thread-safe fashion (if the feature is enabled in git-features, that is).

This is the architecture that was developed during the discovery in #259 .

https://github.com/Byron/gitoxide/blob/38e36a69f5fa6aae2f4cfee7faf11a10cea0f1d0/experiments/odb-redesign/src/lib.rs#L608-L676

### Tasks

* [x] thread-local ref namespaces in `git-repository`
* [x] general ref store (basis)
   * learned that it's currently a little unclear how ref-table will work and handle its shared state. Will it offload this to parameters like the file store? Or will it keep things internal right away? The latter is the preference currently, and if so it would serve as its own handle while being able to efficiently update its internal data structures after writing.
* [x] file db with shared mutable state for it to be doing the right thing by default
   * [x] keep previous `packed` parameter accessible in a somewhat lower level method for those who build abstractions on top.
   * [x] make using cached shared packs possible, similar to snapshots.
* [x] get latest version of this back into `link-git` of `radicle-link` - [in progress](https://github.com/radicle-dev/radicle-link/pull/792) - using mailing list based workflow. Now just a few patches without the upgrade, so nothing else to be done here.
