### ISSUE TITLE
MultiPack index support

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#279]
MultiPack indices are saving resources and speed up object access, they are less common locally but great on the server.

### Tasks

* [x] `multi_index::File` as a way to read the file format
* [x] #282 
* [x] multi-index writing
* [x] integration into `git_odb::Store`
* [x] assure packs can be built when a multi-pack index is present
* [x] optional light-weight verification similar to what git does

**Comment by Byron** [comment]
@avoidscorn I thought I'd share with you some improvements made to the handling of chunk files. Now there is a `git-chunk` crate which facilitates reading and writing of chunk files. The facilities for reading are already used by `git-commitgraph`, while the ones for writing are demoed [when writing multi-pack indices](https://github.com/Byron/gitoxide/blob/41373274fc7f23e3fed17dc52e3e3e94c2e9e41a/git-pack/src/multi_index/write.rs#L128-L192). In case commitgraph writing of of interest to you, I highly recommend taking a look at `git-chunk` as it should make that easier. In any case, have a great new year 2022.
