### ISSUE TITLE
multi-index verification

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#282]
Currently multi-indices can't be verified, but there is nothing preventing this.

### Tasks

* [x] verify the file itself with its checksum. Reuse and deduplicate code from index/verify
* [x] verify integrity by doing the same for each index the multi-file refers to
* [x] add multi-index support to pack-verify 
* [x] add journey test for that and figure out a way to write it as JSON and for humans (probably after we can write multi-indices ourselves from a set of packs)
