### ISSUE TITLE
non-bare clone

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#303]
Clone an entire repository via `gix repository clone` and checkout a working tree along with a valid index.

### Tasks

* **git-odb**
  * [x] all docs, sans examples
  * [x] Rename pack data/pack index `Kind` to `Version` or similar, because that's what it really is.
* **git-object** refactor
  * [x] split `Id` and everything hash related into `git-hash`
  * [x] use `git-hash` inside of `git-features`, remove cycle
* **git-config**
  * [x] Thanks to a generous contribution it's mostly done and well on the way
  * [ ] Push it towards 1.0
  * [ ] `Config` type which integrates multiple files into one interface, much like a *multi* version of `File`
  * [x] Make `gix organize` use `git-config` on single files (the repository configuration)
* **git-ref**
  * [x] transactional creation of refs
  * [x] iteration of refs
* **git-index**
  * [ ] Create an index from tree
* **git-bitmap**
  * [x] pieces needed for git-index to work.
* **git-worktree**
  * [ ] checkout an index
* **git-repository**
  * [x] instance for a valid looking repository
    * [ ] support shallow repos/references
  * [ ] create-update refs as received from clone/git-receive-pack safely (i.e. with required locking)
  * [ ] clone from https remote
* **gix repository clone**
  * [ ] try initializing repo on output path - if so, use that to learn about pack location and place new pack there, allow Repo to create refs somehow.
    * _probably this is done using the repository itself, which steers the whole process and injects it's own delegates_.
  * [ ] otherwise create the scaffolding needed for a new repository, probably based on `init` implementation
* **gix pack receive**
  * [x] resolve thin pack with Bundle

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2778). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
