### ISSUE TITLE
repository FSCK

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#304]
Check the integrity of an entire repository using `gix repository verify`

### Tasks

* **multi-db** (incorporate object lookup for loose objects and packs)
  * [x] multi-threaded
  * [x] delta-tree cache for speedups
  * [x] fs-check - verify all object content of a git repository
    * probably this should be based on indexed pack traversal for maximum decoding speed and not on individual
      object lookup
* [ ] ref-validity check by traversing everything, including reflog, checking reachability of objects accordingly
* what about multiple work-trees and submodules?

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2777). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
