### ISSUE TITLE
Show changes in various forms

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#305]
Run something like a `git status` and `git show`, implementing differences between `tree - tree - index - worktree`.

### Assorted Tasks 

* [x] diff trees with trees
* [x] diff blobs with blobs (using `imara-diff`)
* [ ] a complete enough index implementation (see #293 )
* [ ] an understanding on how worktrees work (also consider `git worktree`) in conjunction git-index (see #301)
* [ ] diffing of worktree -> index -> tree

**Comment by Byron** [comment]
Superseded by #301 .
