### ISSUE TITLE
client push to remote

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#306]
As in `git push`.

### Tasks 

* **git-odb**
  * [x] basic pack generation based on tree-diff or tree-traversal
* [x] **Traversal** (as building blocks to feed pack generation)
  * [x] Traverse a commit graph (look around to see what's common, if in doubt walk back the commit graph and see how to deal with branching)
  * [x] Traverse trees
  * [ ] best-fit delta objects creation using the [similar][sim-crate]

* **git-protocol**
  * [ ] `ReceivePack` logic for V1 and V2
  * [ ] _async_ & _blocking_ negotiation of commits

**Comment by erlend-sh** [comment]
As he said on Discord, this is apparently one of the key features needed for [jujutsu](https://github.com/martinvonz/jj) by @martinvonz to seriously consider using gitoxide.

**Comment by martinvonz** [comment]
Hi, Byron (and others). Jujutsu/jj has come a long way since last time we talked (https://github.com/Byron/gitoxide/discussions/93#discussioncomment-1782772). It's far from just my hobby project and 20% project now. There are several contributors and many users (hard to say how many). Also see our plans for jj at Google from my presentation at Git Merge in September: [recording](https://www.youtube.com/watch?v=bx_LGilOuE4) and [slides](https://docs.google.com/presentation/d/1F8j9_UOOSGUN9MvHxPZX_L4bQ9NMcYOp1isn17kTC_M/edit?usp=sharing). You could use jj to develop Gitoxide itself :) Feedback welcome, of course.

As @erlend-sh said, and as I said last time, support for push is probably the most important feature we're missing from Gitoxide. I saw that Gitoxide will soon be used in `cargo`. That's very exciting news! I understand that that's going to be a priority in the near future. I just hope that push support will be a priority soon thereafter. I think it would be beneficial to both projects if jj could switch over to Gitoxide.

**Comment by Byron** [comment]
Thanks for chiming in, and thanks for posting presentation and slides, I will watch it to get an overview of `jj` and maybe a better understanding where `gitoxide` will fit in.

>  I just hope that push support will be a priority soon thereafter. I think it would be beneficial to both projects if jj could switch over to Gitoxide.

I agree, and would love to make it happen as well. If the Rust Foundation grants pan out, `push` unfortunately will still not be on the roadmap directly as I will be busy removing `git2` from `cargo` entirely, @pascalkuthe will be speeding up pack creation with server-side tech and maybe provide an MVP of `gix upload-pack`, while @SidneyDouw will keep driving the oxidization of high-profile projects. The latter could involve `push` functionality, but it's very unlikely.

That said, I find `push` missing as well and I will do my best to get it ready somehow, having it would make the client side feel much more complete before and I'd love `jj` to get even more rusty :D. Let's see what happens.

**Comment by Byron** [comment]
There seems to be [a setting for that](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushnegotiate). When fetching, and when negotiating properly, one is actually independent of what one *thinks* the server state is in favor what the the server tells us about its state and which objects we actually have (as opposed to what we think we have).
Pushes are by default dependent on our last known state of it, but there seem to be cases when this is not good enough or often leads to less than optimal packs.

**Comment by nixpulvis** [comment]
What's a realistic plan for progress on this?

I have recently started using `gix` for a project I'm working on with the intent to use git as the method of synchronizing local clients with explicit merge conflicts. Push is critical to this, and in the interim I'll be forced to tarball and transport the bytes myself. Before I spend a lot of effort optimizing that path, I'd rather just use push/pull and the mechanisms git provides.

I've seen #2538, but I'm hesitant to really investigate it too deeply since it's a massive code dump, and I assume a more progressive implementation would be needed to be reviewed and accepted here.

**Comment by Byron** [comment]
I still have no immediate need for good push, but I also think given the changes we are all experiencing, it's something that can happen earlier than later. It still needs to be reviewed and that is now the new bottleneck for everything.

My recommendation is to have it implemented yourself first and use that instead, maybe from there it can be contributed back.

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2776). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
