### ISSUE TITLE
Server-side of fetch/pull

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#307]
What would be needed to allow a server to send a pack?

### Server fetch/pull (server to client)

* **git-odb**

The below is a very early draft - it would be better to study existing implementations first to get a better overview on what (not) to do.
This one starts with the fun part to allow writing tests early and experiment with different diff algorithms and potentially their performance.
  
* [x] generate a pack from objects received by an iterator producing (see [issue][pack-mvp])
  * [x] base objects only
  * [x] re-use existing delta objects
  * [x] A mechanism to declare some bases to be 'out of pack' for thin pack support
* [x] **Iterator** to feed pack generation efficiently
* [x] pack creation

[pack-mvp]: https://github.com/Byron/gitoxide/issues/67

* **git-transport**

Certainly needs more research, but roughly…
  
* [ ] Server side `accept()`
  * [ ] http(s)
  * [ ] ssh
  * [ ] ~~daemon~~ probaby only used in testing, and we might implement it if it's useful for us as well
  
* **git-protocol**
  
  * [ ] Server side chatter to negotiate a pack for
    * [ ] protocol V2
    * [ ] protocol V1 (_probably not worth it, let's see_)
  
* **gix-serve**

Probably more like a toy at first merely for testing operation against various git clients.
  
  * [ ] A server able to answer via
    * [ ] http(s)
    * [ ] file protocol (or remote invocation via SSH)
  
[sim-crate]: https://crates.io/crates/similar

**Comment by Byron** [comment]
If I understand the question correctly, the answer is yes. The client of `git-transport` could be handled with what's provided by `accept()`, while the actual interaction patterns would be abstracted in `git-protocol`.

**Comment by yurigeinish** [comment]
This is very desirable to be able to quickly implement your own self-hosted git server (existing ones in other langs require too much memory and therefore are a poor fit for cheap vms).

**Comment by willstott101** [comment]
I've been experimenting with writing a server (in a private repo so far). My interest here is in using parts of gix for the protocol, but leaving the storage up to pluggable backends. I'm very curious about git-on-db, and git-on-object-storage, and git-on-kv-store, and mixtures of the three.

I think I have `ls-refs` working and I'm starting to investigate `fetch`. The protocol is very command-based, and in HTTP AsyncRead & AsyncWrite can't really exist at the same time. Regardless we'd want to leave it up to server implementations to authenticate during the connection, find the relevant repo, authorize the parsed command, then hand back to gitoxide to respond.

So for me a sketch might look like this:
* Server parses HTTP headers & path to verify protocol v2, authenticate and authorize
* `async fn read_command(source: AsyncRead) -> Result<Command>`
* Server writes response headers
* `async fn execute_command(cmd: Command, repo: ..., dest: AsyncWrite) -> Result<()>`

It's possible that a sufficiently advanced AsyncWrite could have a buffer and be appended to the HTTP response after writing the headers, I have also spent no time so far learning about the SSH transport. But those are my thoughts so far.

I also have some questions about packfile construction. I haven't spent a great deal of time investigating yet but I currently haven't found much in the existing gitoxide codebase. Especially relating to resolving packfiles between two peers, but there must be some logic in gix for this somewhere. I'll keep looking, and if anyone is particularly interested in collaborating let me know and I can un-private the repo, I'm just quite enjoying the messy private sandpit atm.

**Comment by Byron** [comment]
That's great news! Please be sure to let us know here once the repo goes public!

Regarding the sketch, the server would probably also reject V1 requests. But then, `read_command()` would read the command itself and arguments to it, but I wonder if that's not a liability as it might read more than it has to given that the server might reject the command itself. That probably also depends on what information the server wants to use to reject the command, but I can imagine that a step-wise process would be better. Read the command-name, then read its arguments, but maybe that is implied.

In general, it's probably OK to just cobble it together and then refactor.

##### pack creation

Regarding packs, you can try `gix free pack create` and see from there how the API works. In general, packs can start streaming quickly, but they won't be the most efficient as they don't delta-compress on the fly. But that might even be a beneficial trade-off at first.

##### Transports

You can check the client-side (use `gix --trace clone ssh://…` to see how `ssh` is typically invoked. From there you will see that it definitely requires its own binary, but that should then be the easiest implementation as it's the same as `gix --trace clone file://local/path`. However, getting the server-side SSH server going is probably it's own set of problems to solve.

**Comment by AleDema** [comment]
@willstott101 Have you managed to write a working git server using gix crates? I'm also looking into doing something similar and I'd like to know whether you found any major roadblocks.

**Comment by willstott101** [comment]
I'm afraid I really didn't put a lot of time into it in the end. No major roadblocks, but I only had a super basic fetch functioning. Decided I needed to refactor to a different server lib  and I lost steam when I realized it was time to make integration tests :)

I hope you're planning your work to be open source. I would be interested to pick this up again.

**Comment by AleDema** [comment]
Yes, I do plan on open sourcing it.

@Byron do gix packages already provide the necessary primitives to implement a basic http git server?

**Comment by Byron** [comment]
The packetline format at the lowest level in `gix-packetline` is available, and the client-side of the `fetch` operation is in `gix-protocol`. But there is no client-side push, nor any of the server side implementation.
One would be able to create packs though, so implementing the server-side protocol of say `fetch` would be possible only by implementing the protocol part.

So the answer would be: yes, the necessary primitives are available.

If things have to go fast (as in 'fast' to implement) though, I'd definitely recommend shelling out to `git`.

**Comment by willstott101** [comment]
I've invited both of you to my "mizzle" repo where I was giving it a go. Current license file is MIT but I can make it whatever I don't mind. No guarantee there's anything useful in there 🤷

**Comment by crsche** [comment]
@willstott101 I was thinking of giving my own implementation of a `gix`-backed server a go, would it be possible to please get access to your `mizzle` repo as well?

**Comment by vlad-ivanov-name** [comment]
A while ago I implemented a very crude /info/refs handler in Josh. Very primitive, and relies on collecting capabilities from the actual git-http-backend, but does work for the first stage:

https://github.com/josh-project/josh/blob/master/josh-proxy/src/serve.rs

**Comment by willstott101** [comment]
I have actually recently been experimenting with using Claude Code and general vibe coding to expand mizzle. I have just made it public so you can take a look @crsche 

https://github.com/willstott101/mizzle

Expect:
* overly ambitious architecture
* AI generated code

But it does work I think. Feels pretty gross to release the code under MIT when it's written by models that have obviously been trained on GPL..... but I suppose that's where we're at? Very happy to collaborate on something or tone down on the genericised backend stuff if it's helpful.

Next steps for me:
* Play around with these alternative storage backend ideas
* dogfood
* See what parts of mizzle ought to be upstreamed into gix
* Add more of the features a git forge might need to use (APIs to build servers that offer file contents, commit logs etc)
* Strategise to make mizzle meaningfully more efficient than your run of the mill git server

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2775). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
