### ISSUE TITLE
git-config towards 1.0

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#331]
An issue to see what's missing to make `git-config` comfortably usable by `git-repository`.

###  Tasks

* [x] ❗️a way to know about the source of a value, i.e. it's possible to know which config file is providing an obtained value.
   - this is important for reading values with security implications, so one would avoid accepting values from configuration files not owned by the current user.
   - [x] a way to restrict queries to a sub-set of the available sources
   - [x] #460
anymore as query entails git-sec.
* [x] #459 
* [x] cascading config files (review/validate)
    * [x] `global` config instantiation (the one without a local repository)
    * [x] know which config files to cascade
* [x] handle implicit keys like `k` and `k=` losslessly during serialization
* [x] #456
    * [x] #457
* [x] correct parsing of `Colors` (e.g. hex input, attributes, inverted attributes, order independence) - _validate_
* [x] use `bstr` internally instead of `[u8]`
* ~~[`flock` config files](https://github.com/git/git/blob/master/config.c#L1954:L1954) before reading them~~
    - a linux-specific thread-safety mechanism, with nothing to do with `flock`.
* advanced features
    * [x] #327
    * [x] parse quantities when dealing with integer [as described here](https://git-scm.com/docs/git-config#Documentation/git-config.txt---typelttypegt)
    * [x] include (might require [real-path support](https://github.com/git/git/blob/main/path.c#L731:L731) in path interpolation) (#345)
    * [x] includeIf (don't forget `from_env()` should pick it up too).
        * [x] Assure `incldudeIf` dotted-key notation works for `GIT_CONFIG_KEY` as well, [see TODO and related comment](https://github.com/Byron/gitoxide/pull/432#discussion_r908831861).
    * [x] assure our multi-value implementation allows for [last-one wins semantics](https://github.com/git/git/blob/30cc8d0f147546d4dd77bf497f4dec51e7265bd8/config.c#L2394). They seem to change the order of values.
    * [x] skip [BOM](https://github.com/git/git/blob/master/config.c#L1005:L1005), `unicode-bom` will do the job well.
* [x] comfortable API for accessing values
* [x] validate sub-sections are [case-sensitive](https://github.com/git/git/blob/main/config.c#L44:L44) when reading (and writing)
     - This applies only to legacy sub-section syntax and we don't implement that, comparing case-insensitive instead. Listed in known deviations.
* [x] remove ResolvedConfig entirely - `GitConfig` can do it all
* [x] a minimal `gix repo config` to print all values, helpful to test errors
* [x] review entire API via `cargo doc`

### Related Discussions

- https://github.com/Byron/gitoxide/discussions/166
- https://github.com/Byron/gitoxide/discussions/147
- https://github.com/Byron/gitoxide/discussions/54

### Towards 2.0

- full serde serialization support (maybe) - the current one is only partial.
- resolved config (optimized for reading, no round-tripping) is created directly from parse events (like git does)
- 100% correct date parsing with `git-date`
   -   This includes parsing [expiry dates](https://github.com/git/git/blob/main/config.c#L1373:L1373), probably as its own top-level type in `comfort.rs`.

### Other Ramblings

* Could `git-config` **use self-referentia**l structures like in [`ignore`](https://github.com/rust-lang/thanks/blob/master/mailmap/src/lib.rs) to avoid copying everything into `Cow<'static, [u8]>` effectively.

**Comment by calavera** [comment]
@Byron would it be possible to get a new minor release with the Path value and other improvements in git-config before a 1.0 release? The goal here looks ambitious, and having those improvements before that would be really appreciated.

**Comment by Byron** [comment]
@calavera Of course, no problem at all. Here is a [v0.2](https://github.com/Byron/gitoxide/releases/tag/git-config-v0.2.0) release of the latest improvements. You can let me know if particular features interest you and I will cut a new release once these become available.

**Comment by clarfonthey** [comment]
Figured this might be the best place to say this since I was poking around in the code, thinking of making a tool using it.

I'd like to be able to automatically sort `gitmodules` sections, since it makes things way easier to read. One thing I noticed right now is that there's not actually any way in the existing code to rearrange sections, minus removing and then pushing them again. I figure that with the way the existing code is done, this *probably* won't be too hard, but I wanted to add it here to see what you think.

Since git uses the same format for all its config files, it probably makes sense to add this functionality to the API so that people can use it for custom formatting routines. That said, it would also make sense if it were reserved for 2.0 or 3.0 since it's not explicitly required to get a working git implementation.

**Comment by Byron** [comment]
> I'd like to be able to automatically sort gitmodules sections, since it makes things way easier to read. One thing I noticed right now is that there's not actually any way in the existing code to rearrange sections, minus removing and then pushing them again.

Thanks for your interest! We might start out with a `gix config` like took ourselves not to soon from now if this is an effort you would be interested in joining. Reorganizing sections isn't anything I thought of, but rather printing existing configuration in a format that is easier to read. This would meant to completely re-generate the configuration as is probably by merging all into one, which should make it trivial to change order at this stage as well. In my mind, this happens outside of `GitConfig` though and wouldn't use its serialization capabilities at all.

The reason I wouldn't use `GitConfig` for that is that this tool wouldn't be interested in reproducing the config files verbatim (then it wouldn't be more than a sophisticated `cat`).

That said…

>  I figure that with the way the existing code is done, this probably won't be too hard, but I wanted to add it here to see what you think.

…that could be true and might be worth an experiment. The reason I think this is likely to produce unexpected results _sometimes_ is that these sections know whitespace and comments surrounding them, hence represent a portion of the `config` file. Reorganizing sections _might_ be more like reorganizing patches in the file that haven't necessarily been created to support this.

The above is merely a concern though and there is no way around testing that. So in case you are interested giving that a shot, please be my guest. There is no reason to wait with that till 2.0 or beyond if you'd be giving it a shot yourself, otherwise  I'd agree that it probably won't make it into 1.0.

**Comment by clarfonthey** [comment]
Given your response, I think I will try and implement this at some point, once I have the time. My main thought process is that moving sections with reasonably formatted whitespace should do what makes the most sense, but it's okay if it totally messes up the whitespace of weirdly formatted sections.

The main benefit is for autoformatters, after all, and the expectation is that those would probably mess with whitespace anyway.

**Comment by BlackHoleFox** [comment]
Is there an estimate or idea how much work `includeIf` support is? Seemingly its just a bit of recursion and parsing but I haven't seen how its actually implemented in C git. If its doable, I could make an attempt.

**Comment by Byron** [comment]
It's already [in progress](https://github.com/Byron/gitoxide/pull/432) and maybe you can give it a trial run as well - it should be functional already for the typical cases.

**Comment by BlackHoleFox** [comment]
Oh, I'm just blind then, I suppose. Sorry for the noise. I'll give it a try and see how it goes.
