### ISSUE TITLE
RevSpec parsing

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#413]
### Basic Parsing

It would be great to be part of the development in case you want to open a draft PR sooner than later. Parsing would go into the `git-revision` crate and have the following requirements.

- parse plain bytes (or `&BStr`), not `&str`
- call functions to signal which item was parsed, that is it doesn't parse into a data structure

Also see [this discussion](https://github.com/Byron/gitoxide/discussions/412) for more insights.

* [ ] a callback based parser

### Revision Ranges

**Prerequisistes**
* [ ] Git Revision Parsing - See #408 
* [ ] Git Merge Base - See #409 
* [ ] `..` (two-dot) Range Notation
* [ ] `...` (three-dot) Symmetric Difference Notation

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2774). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
