### ISSUE TITLE
split index support

### ISSUE THREAD

**Issue by SidneyDouw** [Byron/gitoxide#644]
**What is a split index?**

When using a split index the index is split up into two separate files:
  - the split index at `$GIT_DIR/index`
  - the shared index at `$GIT_DIR/sharedindex.<SHA-1>`

The shared index contains all entries while the split index contains only changes. These changes in the split index are occasionally written into the shared index, either "automatically" based on some config settings, or by the `git-update-index` command.

**Tasks**
- [ ] reading
  - [ ] a way to verify which entries are contained in the split index and the shared index in tests
- [ ] writing
  - [ ] resolve a split index into a "regular" index
  - [ ] write split index

**Config Settings**
- `core.splitIndex`
   enables the use of a split index
- `splitIndex.maxPercentChange`
    Percentage threshold of entries in the split index (compared to the shared index) that triggers a flush to the shared index. Defaults to 20.
- `splitIndex.sharedIndexExpire`
   If the modification time of the shared index is older than this value, the shared index will be deleted
   Takes values like "now", "never", "2.weeks.ago" (default). This needs to be parsed.

**References**
- [git-update-index | split index](https://www.git-scm.com/docs/git-update-index#_split_index)
- [git-index | split index / link extension](https://git-scm.com/docs/index-format#_split_index)

**Comment by Byron** [comment]
Moved to [this Feature Proposal Discussion](https://github.com/GitoxideLabs/gitoxide/discussions/2793). This issue is being closed while the proposal is reviewed; it will become an issue again once review is complete.

_AI disclosure: This comment was written and posted by OpenAI Codex on behalf of Byron._
